[".zsh-tools/zaw"]
    type = "archive"
    url = "https://github.com/zsh-users/zaw/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    
[".zsh-tools/z"]
    type = "archive"
    url = "https://github.com/rupa/z/archive/master.tar.gz"
    exact = true
    stripComponents = 1

[".zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
    clone.args = ["--recursive"]

[".vim/bundle/Vundle.vim"]
    type = "archive"
    url = "https://github.com/VundleVim/Vundle.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
